version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/studyt-back
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 2000
      runas: ec2-user