version: '3'
services: 

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    container_name: studyt_message_broker
    command: mongod --quiet --logpath /dev/null
  
  db:
    container_name: studyt_db
    image: mongo
    ports: 
      - 27017:27017

  db_client:
    container_name: studyt_db_client
    image: mongoclient/mongoclient:latest
    depends_on:
      - db
    ports: 
      - 3300:3000

  dev:
    container_name: studyt_api_dev
    build: 
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports: 
      - 1234:1234
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on: 
      - db
      - redis

  prod:
    container_name: studyt_api_prod
    build: 
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports: 
      - 1234:1234
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on: 
      - db
      - redis