version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: studyt_message_broker

  db:
    container_name: studyt_db
    image: mongo
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null

  api:
    container_name: studyt_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1234:1234
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
      - redis
